### ISSUE TITLE
Battery display

### ISSUE THREAD

**Issue by unicorn-bi** [unicorn-bi/Unicorn-Games-Hybrid-Black#2]
Platformer + Puzzle Game BETA 2628

In the Unicorn Recorder the battery status is displayed as full and the Unicorn also blinks cyan which indicates a good battery status. When we want to start the Platformer or Puzzle Game the battery level status is displayed as empty and after calibration the software says to "Charge" the battery. We are stuck in the calibration stage

**Comment by BernhardWong** [comment]
I cannot reproduce the bug. I quickly checked with a Unicorn Hybrid Black, and everything is functioning fine. I was able to run the Puzzlegame, Platformer, and BrainBuddy without any issues.

Regarding the software that indicates "charge" for the battery, I am unsure which one it refers to. These games have been intensively used in various exhibitions.

I recommend asking users to disconnect and unpair the Unicorn Hybrid Black from the laptop, then reconnect it again.

**Comment by flattinger** [comment]
Sorry, our mistake ...we misunderstood the "recharge" command. we can close the case

**Comment by BernhardWong** [comment]
Ok problem solved.
